services:
  api:
    build: .
    container_name: solis-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/solis-backend?schema=public"
      REDIS_URL: "redis://redis:6379"
      PRISMA_CLIENT_ENGINE_TYPE: "binary"
      AWS_S3_BUCKET_NAME: "your-s3-bucket-name"
      AWS_REGION: "your-aws-region"
      AWS_ACCESS_KEY_ID: "your-access-key-id"
      AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
      
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solis-backend
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  redis_data:
